In [40]:
import fasttext
import pandas as pd
import numpy as np
from sklearn import metrics

In [3]:
model = fasttext.load_model("CrawlMergeFasttextEmbeddingv3.bin")

In [4]:
df = pd.read_csv("all_segment_dataset.csv")
df.head()

Question           Intent
0  ខ្ញុំ ចង់ ដឹង ថា សាលា ស៊ីអេឌីធី សិស្ស ដែល ទើប ...  ScholarshipInfo
1  ខ្ញុំ ចង់ ដឹង ថា សាលា ស៊ីអេឌីធី សិស្ស ដែល ទើប ...  ScholarshipInfo
2  ខ្ញុំ ចង់ ដឹង ថា សាលា ស៊ីអេឌីធី សិស្ស ដែល ទើប ...  ScholarshipInfo
3  ខ្ញុំ ចង់ ដឹង ថា សាលា ស៊ីអេឌីធី សិស្ស ដែល ទើប ...  ScholarshipInfo
4  ខ្ញុំ ចង់ ដឹង ថា សាលា ស៊ីអេឌីធី សិស្ស ដែល ទើប ...  ScholarshipInfo

In [9]:
model.get_sentence_vector("តើ អ្នក កំពុង ធ្វើ អ្វី ?")
convertedValues = [model.get_sentence_vector(x) for x in df["Question"].tolist()]

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(df["Intent"])
dff = encoder.transform(df["Intent"])

print(dff)

X_train, X_test, Y_train, Y_test = train_test_split(convertedValues, dff, test_size=0.2, random_state=42)

[50 50 50 ... 53 53 53]


## Logistic Regression with Newton-CG solver

In [16]:
newtonRegg = LogisticRegression(multi_class="multinomial", solver="newton-cg", max_iter=200, warm_start=True, penalty="l2")
newtonRegg.fit(X_train, Y_train)

LogisticRegression(max_iter=200, multi_class='multinomial', solver='newton-cg',
                   warm_start=True)

In [17]:
score = newtonRegg.score(X_test, Y_test)
print(score)
rise = model.get_sentence_vector("តើ សាលា នៅ ណា ?")
ree = newtonRegg.predict([rise])
print(encoder.inverse_transform(ree))

0.9510597966569017
['AskAboutLocation']


In [25]:
newtonRegg.summary()

NameError: name 'newtonRegg' is not defined

In [135]:
rise = model.get_sentence_vector("តើ អាគារ Innovation Center នៅ ណា ?")
ree = newtonRegg.predict([rise])
encoder.inverse_transform(ree)

array(['AskHowToComplain'], dtype=object)

In [19]:
newtonRegg = LogisticRegression(multi_class="multinomial", solver="newton-cg", max_iter=200, penalty="l2")
newtonRegg.fit(X_train, Y_train)

score = newtonRegg.score(X_test, Y_test)
print(score)
rise = model.get_sentence_vector("តើ សាលា នៅ ណា ?")
ree = newtonRegg.predict([rise])
print(encoder.inverse_transform(ree))

0.9510597966569017
['AskAboutLocation']


In [20]:
newtonRegg = LogisticRegression(multi_class="multinomial", solver="newton-cg", max_iter=200, warm_start=True,
                                penalty="none")
newtonRegg.fit(X_train, Y_train)

score = newtonRegg.score(X_test, Y_test)
print(score)
rise = model.get_sentence_vector("តើ សាលា នៅ ណា ?")
ree = newtonRegg.predict([rise])
print(encoder.inverse_transform(ree))

1.0
['AskAboutLocation']


In [21]:
newtonRegg = LogisticRegression(multi_class="multinomial", solver="newton-cg", max_iter=200, penalty="none")
newtonRegg.fit(X_train, Y_train)

score = newtonRegg.score(X_test, Y_test)
print(score)
rise = model.get_sentence_vector("តើ សាលា នៅ ណា ?")
ree = newtonRegg.predict([rise])
print(encoder.inverse_transform(ree))

1.0
['AskAboutLocation']


## Logistic Regression with LBFGS solver

In [21]:
regg = LogisticRegression(multi_class="multinomial", solver="lbfgs", max_iter=500, )
regg.fit(X_train, Y_train)

LogisticRegression(max_iter=500, multi_class='multinomial')

In [22]:
score = regg.score(X_test, Y_test)
print(score)

0.9510597966569017


In [56]:
rise = model.get_sentence_vector("តើ សាលា នៅ ណា ?")
ree = regg.predict([rise])
encoder.inverse_transform(ree)
newList = np.unique(dff)
riseList = encoder.inverse_transform(newList)
riseList = [str(x) for x in riseList]
print(riseList)

['AskAboutAcademicFee', 'AskAboutAccountantRoom', 'AskAboutAccountantRoom ', 'AskAboutAge', 'AskAboutCS_CourseInEachGen', 'AskAboutCarParkingFee', 'AskAboutClubInfo', 'AskAboutCompetition', 'AskAboutDormInfo', 'AskAboutEC_CourseInEachGen', 'AskAboutEnrollmentRequirement', 'AskAboutInterest', 'AskAboutLocation', 'AskAboutMinistry', 'AskAboutMotocycleParkingFee', 'AskAboutParkingPrice', 'AskAboutProvince', 'AskAboutRegisterDate', 'AskAboutSchoolMajors', 'AskAboutStudyHour', 'AskAboutTN_CourseInEachGen', 'AskHowToComplain', 'AskWhereHRRoomIs', 'AskWhetherJobAnnoucementExist', 'AskWhetherPoepleWorkonExactDate', 'AskWorkingDate', 'AskaboutFemaleDressCode', 'AskaboutMaleDressCode', 'FindAnnouncementInfo', 'FindCSInfo', 'FindClub', 'FindClubRoom', 'FindCurrentTime', 'FindECInfo', 'FindEnrollmentLocation', 'FindResearcherRoom', 'FindTNInfo', 'FindTSC', 'FindTotalStudents', 'FindbusStationNearCADT', 'IsCanteenExist', 'IsExistDoorExit', 'IsFootballFieldExist', 'IsLibraryExist', 'IsMinistryExist'

In [58]:
y_pred = regg.predict(X_test)
print(metrics.classification_report(Y_test, y_pred,target_names=riseList))

                                 precision    recall  f1-score   support

            AskAboutAcademicFee       1.00      0.26      0.42        19
         AskAboutAccountantRoom       0.55      0.86      0.67        14
        AskAboutAccountantRoom        0.00      0.00      0.00        16
                    AskAboutAge       1.00      1.00      1.00        27
     AskAboutCS_CourseInEachGen       1.00      1.00      1.00        27
          AskAboutCarParkingFee       0.97      1.00      0.98       562
               AskAboutClubInfo       0.00      0.00      0.00        16
            AskAboutCompetition       1.00      0.10      0.18        31
               AskAboutDormInfo       1.00      1.00      1.00       325
     AskAboutEC_CourseInEachGen       0.00      0.00      0.00        14
  AskAboutEnrollmentRequirement       0.85      1.00      0.92       299
               AskAboutInterest       1.00      0.76      0.86        29
               AskAboutLocation       0.97      0.

/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [83]:
rise = model.get_sentence_vector("សាលា មាន អាហារូបករណ៍ ទេ")
ree = regg.predict([rise])
encoder.inverse_transform(ree)

array(['ScholarshipInfo'], dtype=object)

In [23]:
rise = model.get_sentence_vector("នៅ ទី ណា បន្ទប់ TSC")

ree = regg.predict([rise])
encoder.inverse_transform(ree)

array(['FindTSC'], dtype=object)

In [124]:
rise = model.get_sentence_vector("តើ បន្ទប់ទឹក នៅ ឯណា ?")
ree = regg.predict([rise])
encoder.inverse_transform(ree)

array(['AskAboutLocation'], dtype=object)

In [130]:
rise = model.get_sentence_vector("តើ ខ្ញំុ ត្រូវ បង់ ប្រាក់ នៅ ឯ ណា?")
ree = regg.predict([rise])
encoder.inverse_transform(ree)

array(['FindCSInfo'], dtype=object)

In [133]:
rise = model.get_sentence_vector("តើ អាគារ Innovation Center នៅ ណា ?")
ree = regg.predict([rise])
encoder.inverse_transform(ree)

array(['AskHowToComplain'], dtype=object)

## SVC Model

In [139]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

labelCoder = LabelBinarizer()
dffff = labelCoder.fit_transform(df["Intent"])
print(dffff)
X_train, X_test, Y_train, Y_test = train_test_split(convertedValues, dffff, test_size=0.2, random_state=42)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [140]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

clf = make_pipeline(StandardScaler(), SVC(gamma="auto"))
clf.fit(X_train, Y_train)

ValueError: y should be a 1d array, got an array of shape (23211, 54) instead.

In [89]:
print(clf.score(X_test, Y_test))

1.0


In [91]:
rise = model.get_sentence_vector("សាលា មាន អាហារូបករណ៍ ទេ")
ree = clf.predict([rise])
encoder.inverse_transform(ree)

array(['FindCSInfo'], dtype=object)

## K-Nearest Neighbor

In [99]:
from sklearn.neighbors import KNeighborsClassifier

print(len(df["Intent"].unique()))

clf = KNeighborsClassifier(10)
clf.fit(X_train, Y_train)


54


KNeighborsClassifier(n_neighbors=10)

In [100]:
clf.score(X_test, Y_test)

0.9843184559710495

In [108]:
rise = model.get_sentence_vector("នៅ ទី ណា បន្ទប់ TSC")

ree = clf.predict([rise])
encoder.inverse_transform(ree)

array(['FindResearcherRoom'], dtype=object)

## One for all method

In [14]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(convertedValues, dff, test_size=0.2, random_state=42)

clf = OneVsRestClassifier(LogisticRegression(max_iter=300)).fit(X_train, Y_train)

In [59]:
clf.score(X_test, Y_test)

newList = np.unique(dff)

riseList = encoder.inverse_transform(newList)
riseList = [str(x) for x in riseList]

In [62]:
y_pred = clf.predict(X_test)
print("Accuracy: ", metrics.accuracy_score(Y_test,y_pred))

print(metrics.classification_report(Y_test,y_pred, target_names=riseList))

Accuracy:  0.937101499224539
                                 precision    recall  f1-score   support

            AskAboutAcademicFee       1.00      0.05      0.10        19
         AskAboutAccountantRoom       0.59      0.71      0.65        14
        AskAboutAccountantRoom        0.00      0.00      0.00        16
                    AskAboutAge       1.00      0.93      0.96        27
     AskAboutCS_CourseInEachGen       1.00      1.00      1.00        27
          AskAboutCarParkingFee       0.97      1.00      0.98       562
               AskAboutClubInfo       0.00      0.00      0.00        16
            AskAboutCompetition       1.00      0.10      0.18        31
               AskAboutDormInfo       0.99      1.00      1.00       325
     AskAboutEC_CourseInEachGen       0.00      0.00      0.00        14
  AskAboutEnrollmentRequirement       0.84      1.00      0.91       299
               AskAboutInterest       1.00      0.45      0.62        29
               AskAbo

/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [20]:
rise = model.get_sentence_vector("នៅ ទី ណា បន្ទប់ TSC")

ree = clf.predict([rise])
encoder.inverse_transform(ree)

array(['FindTSC'], dtype=object)

## Perceptron

In [68]:
from sklearn.linear_model import Perceptron

In [79]:
perceptron = Perceptron(random_state=42,penalty="l1")
perceptron.fit(X_train,Y_train)

perceptron.score(X_test,Y_test)

0.8662760641047734

In [ ]:
# L1 = 0.8662760641047734
# L2 penalty = 0.9410649663966913
# elasticnet = 0.9288299155609168

In [77]:
y_pred = perceptron.predict(X_test)

print("Accuracy: ", metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test,y_pred,target_names=riseList))

Accuracy:  0.9410649663966913
                                 precision    recall  f1-score   support

            AskAboutAcademicFee       1.00      0.42      0.59        19
         AskAboutAccountantRoom       0.56      0.71      0.63        14
        AskAboutAccountantRoom        1.00      0.44      0.61        16
                    AskAboutAge       1.00      1.00      1.00        27
     AskAboutCS_CourseInEachGen       1.00      1.00      1.00        27
          AskAboutCarParkingFee       1.00      0.99      1.00       562
               AskAboutClubInfo       1.00      0.62      0.77        16
            AskAboutCompetition       0.92      0.77      0.84        31
               AskAboutDormInfo       1.00      1.00      1.00       325
     AskAboutEC_CourseInEachGen       0.00      0.00      0.00        14
  AskAboutEnrollmentRequirement       0.96      0.93      0.94       299
               AskAboutInterest       1.00      1.00      1.00        29
               AskAb

/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

## One for One method on Logistic Regression

In [63]:
from sklearn.multiclass import OneVsOneClassifier

In [64]:
oneForOne = OneVsOneClassifier(LogisticRegression(max_iter=300)).fit(X_train,Y_train)

oneForOne.score(X_test, Y_test)

0.9057384111666379

In [67]:
y_pred = oneForOne.predict(X_test)
print("Accuracy: ", metrics.accuracy_score(Y_test,y_pred))

print(metrics.classification_report(Y_test,y_pred, target_names=riseList))

Accuracy:  0.9057384111666379
                                 precision    recall  f1-score   support

            AskAboutAcademicFee       0.00      0.00      0.00        19
         AskAboutAccountantRoom       0.00      0.00      0.00        14
        AskAboutAccountantRoom        0.00      0.00      0.00        16
                    AskAboutAge       1.00      0.52      0.68        27
     AskAboutCS_CourseInEachGen       1.00      0.85      0.92        27
          AskAboutCarParkingFee       0.92      1.00      0.96       562
               AskAboutClubInfo       0.00      0.00      0.00        16
            AskAboutCompetition       0.00      0.00      0.00        31
               AskAboutDormInfo       0.87      1.00      0.93       325
     AskAboutEC_CourseInEachGen       0.00      0.00      0.00        14
  AskAboutEnrollmentRequirement       0.74      1.00      0.85       299
               AskAboutInterest       0.00      0.00      0.00        29
               AskAb

/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/icyfrost/anaconda3/envs/group2/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le